### ISSUE TITLE
ng-required doesn't work as usual

### ISSUE THREAD

**Issue by johannesjo** [vitalets/checklist-model#45] opened 2014-09-24 22:17 UTC
If i need at least one checkbox to be checked, how would I go about validation? ng-required does not seem to work as usual.

**Comment by mendelk** [comment] 2015-01-20 16:38
:+1:

**Comment by poths** [comment] 2015-02-09 12:28
+1

**Comment by TimSin** [comment] 2015-02-10 14:22
+1

**Comment by TimSin** [comment] 2015-02-10 15:16
There is a work around to this, it's not ideal but allows validation to take place. An example of this is below:

```
 <div class="checkbox" ng-repeat="cat in op_cat">
     <label for="cat_{{cat.id}}">
         <input type="checkbox" id="cat_{{cat.id}}" 
            checklist-model="entity.categories" 
            checklist-value="cat"
            ng-required="!(entity.categories && entity.categories.length > 0)"
            title='Please select one or more categories' />
            {{cat.name}}
     </label>
  </div>

```
It's fairly self explanatory, but the important bit is the ng-required attribute - this dynamically changes between true and false depending on whether there are any categories selected, allowing validation to occur when there are no checkboxes checked.

That said, it's quite simplistic so it would be good to see fuller support for validation implemented in this otherwise handy library.

**Comment by niemyjski** [comment] 2015-02-10 15:41
Yeah, this is what I did but there are some issues where only some of
the checkboxes are highlighted as required when validation fails.

On 2/10/15, TimSin <notifications@github.com> wrote:
> There is a work around to this, it's not ideal but allows validation to take
> place. An example of this is below:
>
> ```
>  <div class="checkbox" ng-repeat="cat in op_cat">
>      <label for="cat_{{cat.id}}">
>          <input type="checkbox" id="cat_{{cat.id}}"
>             checklist-model="entity.categories"
>             checklist-value="cat"
>             ng-required="!(entity.categories && entity.categories.length >
> 0)"
>             title='Please select one or more categories' />
>             {{cat.name}}
>      </label>
>   </div>
>
> ```
> It's fairly self explanatory, but the important bit is the ng-required
> attribute - this dynamically changes between true and false depending on
> whether there are any categories selected, allowing validation to occur when
> there are no checkboxes checked.
>
> That said, it's quite simplistic so it would be good to see fuller support
> for validation implemented in this otherwise handy library.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/vitalets/checklist-model/issues/45#issuecomment-73715950


-- 
Thanks
-Blake Niemyjski

**Comment by sazo** [comment] 2015-02-15 17:20
duplicate of #15. Will stay open because of the good information

**Comment by eskatos** [comment] 2015-02-28 13:29
:+1:

**Comment by luisrudge** [comment] 2015-03-04 06:31
:+1:

**Comment by luisrudge** [comment] 2015-03-04 06:37
@TimSin this approach doesn't set $touched until every checkbox is checked

**Comment by szkrd** [comment] 2015-05-22 12:50
Not sure if it helps, but I ended up using an aggregator input:

view:
```
  <li ng-repeat="category in categories">
      <input type="checkbox" checklist-model="data.categories" checklist-value="category.id">
      {{category.caption}}
  </li>
  <input type="checkbox" name="hasCategories" ng-model="hasCategories" required>
```
controller:
`$scope.$watch('data.categories.length', (val) => $scope.hasCategories = val > 0);`

The helper input is hidden, dirty/broken item focusing is redirected using a directive.

**Comment by beradrian** [comment] 2015-08-10 18:59
I think the best way to tackle this will be to implement checklist-minlength and checklist-maxlength. But what should happen, when you specify different values on different checkboxes bound to the same checklist-model?

As an example

    <input type="checkbox" checklist-model="selected" checklist-minlength="1" value="a"/>
    <input type="checkbox" checklist-model="selected" checklist-minlength="2" value="b"/>

I would tend to go for the simpler solution and do the validation using the value specified on the checkbox that is just clicked. But this could tend to be confusing.

**Comment by beradrian** [comment] 2015-08-10 19:11
By the way, `INPUT[checkbox]` does not support `ng-required`: https://docs.angularjs.org/api/ng/input/input%5Bcheckbox%5D

**Closed** 2015-08-11 17:40 UTC
Labels: duplicate

**Comment by beradrian** [comment] 2015-08-11 17:42
Please continue the discussion at https://github.com/vitalets/checklist-model/issues/15 to decide on how to implement this feature.

**Comment by gotstu** [comment] 2015-12-11 00:51
Thanks @TimSin . Simple and effective

**Comment by beradrian** [comment] 2015-12-11 10:24
Here's another example on how to do validation: http://jsfiddle.net/beradrian/nbwcbejw/.
I don't think that is correct, not even semantically to have each checkbox required, because what you practically want is to have *at least one* selected.

**Comment by nitintutlani** [comment] 2016-02-13 07:10
@beradrian your fiddle works for me :)
I just needed to add same validation on `ng-init`: http://jsfiddle.net/nbwcbejw/2/
