### ISSUE TITLE
Missing required/minlength/maxlength functionality

### ISSUE THREAD

**Issue by himdel** [vitalets/checklist-model#15] opened 2014-02-15 11:55 UTC
There seems to be no way to make checklist-model require at least 1 checkbox to be selected.

I tried creating a checklist-required directive, but with no success as it doesn't use ngModel so I can't call ctrl.$setValidity.

**Comment by dsh** [comment] 2015-01-13 21:30
+1 to have this built in, though alexleekt's solution worked perfectly.

**Comment by skalb** [comment] 2015-02-16 23:12
I ended up modifying the directive a bit to support a 'checklist-minimum' attribute (haven't had time to make a PR yet)

You can see it in action here: http://plnkr.co/edit/uau6JpMgfmOwJ60AdAKt?p=preview

**Comment by eskatos** [comment] 2015-02-28 13:29
:+1:

**Comment by beradrian** [comment] 2015-08-10 18:59
I think the best way to tackle this will be to implement checklist-minlength and checklist-maxlength. But what should happen, when you specify different values on different checkboxes bound to the same checklist-model?

As an example

    <input type="checkbox" checklist-model="selected" checklist-minlength="1" value="a"/>
    <input type="checkbox" checklist-model="selected" checklist-minlength="2" value="b"/>

I would tend to go for the simpler solution and do the validation using the value specified on the checkbox that is just clicked. But this could tend to be confusing.

**Comment by beradrian** [comment] 2015-08-10 19:10
By the way, `INPUT[checkbox]` does not support `ng-required`: https://docs.angularjs.org/api/ng/input/input%5Bcheckbox%5D

**Comment by beradrian** [comment] 2015-08-11 17:38
There is a [pull request](https://github.com/vitalets/checklist-model/pull/79) for `checklist-max-length`, but before merging it, I would like to hear more opinions on the questions above.

**Comment by beradrian** [comment] 2015-08-11 17:42
I closed https://github.com/vitalets/checklist-model/issues/45, as a duplicate.

**Comment by felixfbecker** [comment] 2015-08-20 18:13
@beradrian I dont quite get your question. All values get pushed or pulled from the same array (model). The length of this array needs to be checked whenever the user tries to click a checkbox.

**Comment by beradrian** [comment] 2015-08-22 08:36
Look at the example that I gave above. There are two checkboxes specifying the same checklist-model, but with different values for the checklist-min-length attribute.

**Comment by Si1kIfY** [comment] 2015-08-28 01:35
Agreed this should be included but @alexleekt's solution worked great :+1:

**Comment by beradrian** [comment] 2015-09-21 12:41
Before including this I would like to hear some feedback based on the examples that I gave above.

**Comment by cokuyan** [comment] 2015-11-03 21:39
I'm not sure you should be able to specify different lengths for the same checklist-model. I would prefer an error message if that happens, but you could also just have it take the last defined value.

**Comment by beradrian** [comment] 2015-11-04 08:14
@cokuyan, you can specify different lengths to two checkboxes associated with the same checklist-model - just see above. I would also prefer an error, but the values are dynamic and they all have to be scanned each time - which is time consuming. I could compare the value only with the last used one, but then the error message will appear only when that checkbox is clicked.

The fast solution is not to use the last defined value, but the value defined for that specific checkbox. If you look at my above example, when you click checkbox a, the min-length considered will be 1, as opposed when you click checkbox b, where the min-length will be 2. I'm afraid that this will be confusing.

Any other ideas?

**Comment by cokuyan** [comment] 2015-11-04 15:37
@beradrian, I see what you mean after looking at the code. The fast solution would be confusing since it would allow multiple allowed lengths depending on the order that the checkboxes are checked. Another solution I'm thinking about would take away from the flexibility of the code by imposing a sort of higher level controller that pays attention to the state of the checklist-model instead of leaving that to the individual checkboxes.

I'll think on it a bit more, though, since this is a pretty interesting problem.

**Comment by beradrian** [comment] 2015-11-05 09:15
The higher level controller is a solution that I also thought - it was a way to implement the option of scanning the values. But it's time consuming and I don't think that a simple checkbox(es) should introduce this kind of overhead.

I know that the problem is interesting, there are few solutions, but I haven't implemented it, as I wanted to have the community opinion first and have it implemented in such way that it would be easy to use, not confusing and without a huge performance penalty.

**Comment by darrenshrwd** [comment] 2015-11-11 04:36
Thread called `required`, but I understand that checklist-minlength covers the requirement, as a 'end user' not having more than a cursory look at the implementation:

A: I would not care if I had to add an attribute to a higher up element. HOWEVER I certainly would care if this had to be an immediate parent as I wrap the inputs in labels.  I'd would probably dislike any other significant restriction that may be required on HTML structure. Also given the current ease of use...if it is necessary the attribute would want to be optional if not required (i.e. not break the current API).

B: I would also not mind if I have to add the attribute to each input, notably doing so is congruent with adding required to each input for radio inputs.

If doing B then I don't see issue with using checklist-minlength and having different values...surely a different value is a user error so either throw an error or us the lowest value found?

**Comment by beradrian** [comment] 2015-11-11 06:52
@darrenshrwd, first of all thank you for the valuable input.
As `checklist-minlength=1` will be equivalent with `required`, I will implement only the former.
The only concern I had with throwing an error was the fact that I have to scan all the values, which is time-consuming.

**Comment by darrenshrwd** [comment] 2015-11-12 11:20
Oh yeah I get that now, sorry I see you pointed it out earlier. If helps performance then could just use attribute on the first checkbox and ignore any others? (rather than check all and throw error.

Agree required is urm not required. Would it still work with ng-messages in some way though?..or I best just use alexleekt's solution.

**Comment by beradrian** [comment] 2015-11-22 12:19
I implemented `checklist-before-change`, which is evaluated before the change happens and if it evaluates to `false`, the change is not happening anymore.

So maxlength will become something like 

    checkilst-before-change="model.length < maxlength"

What do you think? Should this be enough to consider this issue fixed?

**Comment by cokuyan** [comment] 2015-11-22 20:14
I do like that added functionality. One main problem though is that it does not set the validity of the checkboxes like what `required` does. I guess that could be done in the callback action, however. 

I really hope Angular 2 has better support for checkbox lists...

**Comment by beradrian** [comment] 2015-11-23 07:32
@cokuyan, use checklist-before-change, actually you won't allow to become invalid. Unless this is the default value, but then you can set the initial validity.

**Comment by darrenshrwd** [comment] 2015-11-27 06:16
@alexleekt  @dsh I'm just trying to use that solution, but it's not working and I don't get it...ng-required does not seem to be allow on type="checkbox" as per: https://docs.angularjs.org/api/ng/input/input%5Bcheckbox%5D

**Comment by beradrian** [comment] 2015-11-27 08:49
At this moment, you have the following options:
- specify your own `ng-model` and play with it
- use @alexleekt solution
- use the new `checklist-before-change`
I would say that we can close this issue. If you're still unhappy with any of these, please comment and reopen the issue. Thanks!

**Closed by beradrian** 2015-11-27 08:49 UTC
Labels: enhancement, need more information

**Comment by beradrian** [comment] 2015-12-08 13:06
I added an example on how to use required: http://jsfiddle.net/beradrian/7wt9q1ev/

**Comment by gotstu** [comment] 2015-12-11 01:09
I just used a requiredArray directive I was already using.
<div class="checkbox" ng-repeat="payCenter in payCenters">
                <label>
                    <input name="payCenters" 
                           type="checkbox" 
                           ng-required="!(user.payCenters && user.payCenters.length > 0)" 
                           checklist-model="user.payCenters" 
                           checklist-value="payCenter"
                           requiredArray>
                    <strong>{{payCenter.Name}}</strong>
                </label>
            </div>       

.directive('requiredArrayValidator', function () {
    return {
      require: 'ngModel',
      link: function ($scope, $elm, $attrs, $ctrl) {
        $ctrl.$validators.requiredArrayValidator = function (modelValue, viewValue) {
          return viewValue.length > 0;
        };
      }
    };
  })

**Comment by beradrian** [comment] 2015-12-11 10:29
@gotstu, that's actually a nice idea and you can easily extend it to use checklist-min/max-length. Only one thing, require should be 'checklistModel'. 
If you have an idea on how to solve possible inconsistencies between values on different checkboxes, then it would be good. Then if you also want to build these directive, I will consider include them into a future release.

**Comment by gotstu** [comment] 2015-12-11 17:28
@beradrian It works with ng-model. Have not looked into why but it does. Thanks for min/max sug
