### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by StateBarofArizona** [vitalets/checklist-model#84] opened 2015-08-19 19:56 UTC
Does not appear to work with the latest version of AngularJS.  Using a hard coded checkbox and still, nothing shows up.

                <div class="form-control checkbox">
                    <label><input type="checkbox" checklist-model="formData.CategoryIDees" checklist-value="99">99 Test</label>
                </div>

**Comment by beradrian** [comment] 2015-08-19 21:36
Duplicate of #28.

**Closed by beradrian** 2015-08-19 21:36 UTC
Labels: duplicate
