### ISSUE TITLE
Malfunctions, when used with angular-translate

### ISSUE THREAD

**Issue by mavarazy** [vitalets/checklist-model#95] opened 2015-10-02 16:43 UTC
With a simple Object, and following markup:

    <label ng-repeat="(key, text) in roles">
        <input type="checkbox" checklist-model="user.roles" checklist-value="key"> {{text}}
    </label>

But when adding properly configured translate:

    <label ng-repeat="(key, text) in roles">
        <input type="checkbox" checklist-model="user.roles" checklist-value="key" translate> {{text}}
    </label>

it does not trigger update events for user.roles anymore

**Comment by beradrian** [comment] 2015-10-05 10:00
Do you have a JSFiddle, Plunkr example or anything alike?

**Comment by pratik14** [comment] 2015-10-17 08:45
@mavarazy Do you want to change value of checkbox along with text?

**Comment by beradrian** [comment] 2015-11-22 12:23
The tests are working and I cannot reproduce this issue. Until more detailed example of the issue is provided, I will close it. Please feel free to reopen it.

**Closed by beradrian** 2015-11-22 12:23 UTC
Labels: need more information
