### ISSUE TITLE
HTML5 compatibility

### ISSUE THREAD

**Issue by raajon** [vitalets/checklist-model#39] opened 2014-07-25 12:04 UTC
Hello i've found such a bug:

this work just fine:
\<input type="checkbox" checklist-model="user.roles" checklist-value="role">

and this crash the application
\<input type="checkbox" x-checklist-model="user.roles" x-checklist-value="role">
\<input type="checkbox" data-checklist-model="user.roles" data-checklist-value="role">

**Comment by sazo** [comment] 2015-02-15 17:06
duplicate of #16

**Closed by sazo** 2015-02-15 17:06 UTC
