### ISSUE TITLE
Hard Return issue

### ISSUE THREAD

**Issue by tedhohio** [vitalets/checklist-model#41] opened 2014-08-26 20:43 UTC
For some reason, when I use the checklist model, everything is on one line.  I have inserted <br /> and <p></p> in everyplace available, but the best I can get is the labels on the next line after the checkboxes.  Everything else is working great.  Any ideas?

Current code is:  
<label ng-repeat="indType in indTypes">
                        <input type="checkbox" checklist-model="selectedTypes" checklist-value="indType"> {{indType.name}}<br />
                    </label>

**Comment by sazo** [comment] 2015-02-15 17:10
i dont quick understand the problem here? is it a styling problem or? could you please make a http://www.plnkr.co to show me what the problem is?

**Comment by beradrian** [comment] 2015-07-29 21:58
As no information was provided for quite some time, I will close this issue. Please feel free to reopen it when providing additional information.

**Closed by beradrian** 2015-07-29 21:58 UTC
Labels: status:need more information
