### ISSUE TITLE
Any chance to preselect boxes when model is already filled?

### ISSUE THREAD

**Issue by lennarterikson** [vitalets/checklist-model#100] opened 2015-10-30 14:51 UTC
First of all thank you for sharing your amazing checklist-model, I was searching for a solution like this for days! 
My question is: Is there is any chance to select the checkboxes when the underlying model changes?
For example:
I receive a list of booked rooms from my REST-API and set it to be my selectedRooms model. I would like the checkboxes of the corresponding rows in my room table to be selected. However even if the underlying model changed, the checkboxes didn't turn into checked-mode.

Do you have any idea how to solve this? Is there a parameter I forgot to add? Or is this behaviour not intended?

**Comment by beradrian** [comment] 2015-11-01 11:10
Actually this is the intended behavior. I don't know your code, but I suspect that you need to call something like scope.$apply().

**Comment by beradrian** [comment] 2015-11-04 12:53
I suspect that you managed to fix it, so I will close it. If you still have problems, please feel free to re-open it.

**Closed by beradrian** 2015-11-04 12:53 UTC
Labels: question
